apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-td5o
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qbgh-tenant/rhtap-demo-app/hacbs-test-project-td5o@sha256:5eab03f9a6b35c4106b8c691252e9fad5b4ef9b200f56ed6e443d98209e579a8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
