apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-td5o
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qbgh-tenant/rhtap-demo-app/hacbs-test-project-td5o@sha256:56abb9a61c5a0160b199a8e049feab9b18086bef4c24fb522e5f53bc7f7376d4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
