apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-td5o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-td5o
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-td5o
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-td5o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-td5o
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qbgh-tenant/rhtap-demo-app/hacbs-test-project-td5o@sha256:56abb9a61c5a0160b199a8e049feab9b18086bef4c24fb522e5f53bc7f7376d4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
